### PR TITLE
Johnathan/environment waypoints

### PR DESCRIPTION
**Pull request by JohnathanGlasgow**
### Summary
This PR contains the environment for the game as well as the spline system to guide the player model up the Gostra pole. It implements the basic gameplay loop and an entry point to the game.

### Current Scene
The most current scene is 'Johnathan_IntegratingSliders'

### Size
I imported the Unity terrain tools, terrain samples, spline package, water shaders, and other assets into the project, so some of these commits are quite large. It may take a few minutes to fetch/pull the branch.

### Changes
Changes introduced:
- Seaside environment for the game
- Spline track from the shore up the pole to guide the player
- Player speed, that is the speed which they move up the spline, decreases relative their Y position
- When speed falls below a threshold, rag doll is triggered
- If player reaches top of pole, rag doll is triggered
- Title screen added
- Meters affect player speed and rotation (Note: I ended up linking the player in the meter scripts rather than vice versa)
- Start, stop, and reset methods for the meters
- Player idles at game start
- Balance meter begins when player reaches the pole
- Camera animation for title screen to gameplay
- Debug panel

The length of the pole, player start position, and camera angle are all easily changed; the current values are not meant to be final.

### New scripts
New scripts:
- FPSCounter.cs
- MoveCamera.cs
- MainManager.cs
- MeterManager.cs
- UIManager.cs
- MoveAlongSpline.cs
- PlayerController.cs (PlayerAnimator was refactored into this script)

### CODE REVIEW

**Comment by JohnathanGlasgow** [comment]
There is an error getting thrown which seems to be a known issue with the Terain Toolbox:
Screenshot 2024-06-06 at 12 04 25 PM


This can supposedly be fixed by going to line 2061 in the script in question and putting `m_PreviewMaterial.DisableKeyword("_SPLATMAP_PREVIEW");` in an else block like this:

```
            if (m_PreviewMaterial == null)
            {
                GetAndSetActiveRenderPipelineSettings();
            }
            else
            {
                m_PreviewMaterial.DisableKeyword("_SPLATMAP_PREVIEW");
            }
```

But that gets reverted when the packages reload so I don't know. The exception doesn't seem to affect anything so I will just leave it for now. Annoying though.

EDIT: After closing the Terrain Toolbox window and restarting the editor, the issue goes away. So it seems to be linked to building the project while the Terrain Toolbox window is open.

**Review by PBWiseman — APPROVED** [review]
Everything looks good. Balancing changes still need to be done but that's for later. The only thing that concerns me is that the terrain seems to have high performance impact. Using the school computers, I went from 20fps to 60fps by disabling it. Can this be optimized easily in a later sprint?

**Comment by JohnathanGlasgow** [comment]
> Everything looks good. Balancing changes still need to be done but that's for later. The only thing that concerns me is that the terrain seems to have high performance impact. Using the school computers, I went from 20fps to 60fps by disabling it. Can this be optimized easily in a later sprint?

Ah okay good to know. Should be able to optimise it. Worst case it can be pre-rendered.

EDIT: I just checked on my computer, M1 macbook air, and I only gained ~12 frames at 1080p with the terrain off.

Its worth noting performance is also affected by the editor window.

**Review by LiamMcKenzie — APPROVED** [review]
I'm really happy with the progress we've made so far. All our features are integrated together nicely.

I like the environment that you added.

I think the game will need to be rebalanced, but all the changes added in this PR are working correctly

**Pull request merged**
