### PR TITLE
Running and balance meters

### LINKED ISSUE #12: Run and Balance meters
### Description:
_Describe the feature you'd like to see added._
- A run meter that you have to hit in time to increase your speed and a balance meter you have to keep in the middle to stay on the pole

### Use Case:
_How will this feature be useful? Include any relevant scenarios or examples._
- Without meters there can be no gameplay

### PR DESCRIPTION
**Pull request by PBWiseman**
This branch has the running and the balance meters.

The running meter fills up and then goes back down either when you hit the interact button (space) or when it goes to the top. Hitting the button when the slider is within the target area is a success and will give you a bonus to movement speed and either hitting the button when it's outside of the area or not hitting the button at all and letting it go to the top is a failure and decreases movement speed. All values with the speed are just there to test the slider out and should be changed later.

The balance meter doesn't start until you get to the log (or hit the button for testing) and once there tries to make you fall by moving back and forward. You can try to keep yourself balanced by tapping left or right arrows which moves the slider a bit each time. If you hit the red zone (the left or right most 10%) then you slip off and it goes all the way to that side.

The combination of both of these is quite difficult to manage but that is what I was going for. A possible change would be to change the severity and speed of the balance meter changing based on how far up the pole you are.

### CODE REVIEW

**Review by JohnathanGlasgow — APPROVED** [review]
The speed bar is great.
The balance mechanic is tough, but the functionality is there and the graphic is good. 
The code looks good and it's nice to see some properties and backing fields being used.

**Review by LiamMcKenzie — CHANGES_REQUESTED** [review]
Overall looks good but I think the balance meter should be changed, its a bit chaotic

here is my idea for the balance meter:
 
# Idea
balance meter moves left automatically when on left side of center. moves right when on right side of center
 
mashing left or right will move cursor by a little bit in the corresponding direction
 
the amount that the cursor moves could be random within a range
 
# Difficulty
moving from the left side to the right side could make the balance meter speed increase.
 
The difficulty would come from mashing to keep up but slowing down when crossing over center
 
The amount the cursor moves could also randomly be double or triple what it normally is (to throw the player off)
 
overall it would be easier to start off but we can add more mechanics later on.

**Comment by PBWiseman** [comment]
> Overall looks good but I think the balance meter should be changed, its a bit chaotic
> 
> here is my idea for the balance meter:
> 
> # Idea
> balance meter moves left automatically when on left side of center. moves right when on right side of center
> 
> mashing left or right will move cursor by a little bit in the corresponding direction
> 
> the amount that the cursor moves could be random within a range
> 
> # Difficulty
> moving from the left side to the right side could make the balance meter speed increase.
> 
> The difficulty would come from mashing to keep up but slowing down when crossing over center
> 
> The amount the cursor moves could also randomly be double or triple what it normally is (to throw the player off)
> 
> overall it would be easier to start off but we can add more mechanics later on.

Good ideas! I have implemented them but I'm not sure if I got the interaction right. I'd love more feedback when you can

**Review by LiamMcKenzie — APPROVED** [review]
This looks great! I like how the meter has a slight animation when pressing directions. I wasn't sure how possible that would be but I think it works.

The difficultly ramps up quite quickly which I like. Later on it might be nice to increase the base speed.

The code in this is great and has very useful comments

**Review by JohnathanGlasgow — APPROVED** [review]
This feels better than before. Ultimately the difficulty increase will be tied to player height so we can iron that out once its merged.

**Pull request merged**
